{% set name = "python-AGS4" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 29fcd06205235437efd25e344e5df427e0e7d10a1b5d09e19f7993fafc15dedc

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - ags4_cli = python_ags4.ags4_cli:main

requirements:
  host:
    - python >=3.7
    - pip
    - poetry
  run:
    - python >=3.7
    - pandas >=1.0,<2.0
    - openpyxl >=3.0,<4.0
    - defusedxml >=0.6.0,<1.0
    - click >=7.0,<9.0
    - rich >=9.0,<13.0

test:
  imports:
    - python_ags4
  requires:
    - pip
  commands:
    - ags4_cli --help

about:
  home: https://gitlab.com/ags-data-format-wg/ags-python-library
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - LICENSE
    - COPYING.LESSER
  summary: A library to read, write, and check AGS4 files using Pandas DataFrames

extra:
  recipe-maintainers:
    - Didymograptus
    - asitha-sena
