{% set name = "python-AGS4" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python_ags4-{{ version }}.tar.gz
  sha256: 3e22d74f808e97daf12f3ed92173179c0e563b4dd65aedae3ee55b36c71d9c13

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - ags4_cli = python_ags4.ags4_cli:main

requirements:
  host:
    - python >=3.8
    - pip
    - poetry
  run:
    - python >=3.8
    - pandas >=2.0
    - openpyxl >=3.0,<4.0
    - defusedxml >=0.6.0,<1.0
    - click >=7.0,<9.0
    - rich >=9.0,<14.0

test:
  imports:
    - python_ags4
  requires:
    - pip
  commands:
    - ags4_cli --help

about:
  home: https://gitlab.com/ags-data-format-wg/ags-python-library
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - LICENSE
    - COPYING.LESSER
  summary: A library to read, write, and check AGS4 files using Pandas DataFrames

extra:
  recipe-maintainers:
    - Didymograptus
    - asitha-sena
